spring:
  profiles:
    active: test
  application:
    name: 小鸟论坛
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      accept-single-value-as-array: true
      accept-empty-array-as-null-object: true

server:
  port: ${SERVER_PORT:8088}
  servlet:
    context-path: /
